<?php

// autoload_static.php @generated by Composer

namespace Composer\Autoload;

class ComposerStaticInitae3d6b2b5e16444d0f8c95c5b51a02a1
{
    public static $prefixLengthsPsr4 = array (
        'l' => 
        array (
            'leggettc18\\SimpleRouter\\' => 24,
            'leggettc18\\SimpleORM\\' => 21,
        ),
        'B' => 
        array (
            'Blog\\' => 5,
        ),
    );

    public static $prefixDirsPsr4 = array (
        'leggettc18\\SimpleRouter\\' => 
        array (
            0 => __DIR__ . '/..' . '/leggettc18/simple-router/src',
        ),
        'leggettc18\\SimpleORM\\' => 
        array (
            0 => __DIR__ . '/..' . '/leggettc18/simple-orm/src',
        ),
        'Blog\\' => 
        array (
            0 => __DIR__ . '/../..' . '/src',
        ),
    );

    public static $classMap = array (
        'Composer\\InstalledVersions' => __DIR__ . '/..' . '/composer/InstalledVersions.php',
    );

    public static function getInitializer(ClassLoader $loader)
    {
        return \Closure::bind(function () use ($loader) {
            $loader->prefixLengthsPsr4 = ComposerStaticInitae3d6b2b5e16444d0f8c95c5b51a02a1::$prefixLengthsPsr4;
            $loader->prefixDirsPsr4 = ComposerStaticInitae3d6b2b5e16444d0f8c95c5b51a02a1::$prefixDirsPsr4;
            $loader->classMap = ComposerStaticInitae3d6b2b5e16444d0f8c95c5b51a02a1::$classMap;

        }, null, ClassLoader::class);
    }
}
