<?php

// autoload_psr4.php @generated by Composer

$vendorDir = dirname(__DIR__);
$baseDir = dirname($vendorDir);

return array(
    'leggettc18\\SimpleRouter\\' => array($vendorDir . '/leggettc18/simple-router/src'),
    'leggettc18\\SimpleORM\\' => array($vendorDir . '/leggettc18/simple-orm/src'),
    'Blog\\' => array($baseDir . '/src'),
);
