<?php return array(
    'root' => array(
        'pretty_version' => 'dev-main',
        'version' => 'dev-main',
        'type' => 'library',
        'install_path' => __DIR__ . '/../../',
        'aliases' => array(),
        'reference' => '3b5c0dfb0df8ac3c77ccd779dfab4bfe1f64978d',
        'name' => '__root__',
        'dev' => true,
    ),
    'versions' => array(
        '__root__' => array(
            'pretty_version' => 'dev-main',
            'version' => 'dev-main',
            'type' => 'library',
            'install_path' => __DIR__ . '/../../',
            'aliases' => array(),
            'reference' => '3b5c0dfb0df8ac3c77ccd779dfab4bfe1f64978d',
            'dev_requirement' => false,
        ),
        'leggettc18/simple-orm' => array(
            'pretty_version' => 'dev-master',
            'version' => 'dev-master',
            'type' => 'package',
            'install_path' => __DIR__ . '/../leggettc18/simple-orm',
            'aliases' => array(),
            'reference' => '0beb8d81dea64c15645221693262c7f64b915bac',
            'dev_requirement' => false,
        ),
        'leggettc18/simple-router' => array(
            'pretty_version' => 'dev-master',
            'version' => 'dev-master',
            'type' => 'library',
            'install_path' => __DIR__ . '/../leggettc18/simple-router',
            'aliases' => array(),
            'reference' => '43e7ca1889d931ee02c7fe9ae526c51bc530b246',
            'dev_requirement' => false,
        ),
    ),
);
